services:
  revers-proxy:
    image: webair/richi-lock-reverse-proxy
    container_name: richi-reverse-proxy
    networks:
      - richi-network
    environment:
      HOST: ${RICHI_HOST}
      UPSTREAM_WEB_SERVICE: web-service:3000
    depends_on:
      - web-service
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  mqtt-broker:
    image: webair/richi-lock-mqtt-broker
    container_name: richi-mqtt-broker
    networks:
      - richi-network
    environment:
      USERNAME: ${MQTT_BROKER_USERNAME}
      PASSWORD: ${MQTT_BROKER_PASSWORD}
    ports:
      - "1883:1883"
    restart: unless-stopped
  web-service:
    image: webair/richi-lock-web-service
    container_name: richi-web-service
    networks:
      - richi-network
    environment:
      WEB_SERVICE_HOST: ${RICHI_HOST}
      MQTT_BROKER_HOST: mqtt-broker
      MQTT_BROKER_USERNAME: ${MQTT_BROKER_USERNAME}
      MQTT_BROKER_PASSWORD: ${MQTT_BROKER_PASSWORD}
    depends_on:
      - mqtt-broker
    ports:
      - "3000:3000"
    restart: unless-stopped

networks:
  richi-network:
    driver: bridge
