services:
  revers-proxy:
    build: ./reverse-proxy
    restart: no
  mqtt-broker:
    build: ./mqtt-broker
    restart: no
  web-service:
    build: ./web-service
    restart: no
  web-client:
    build: ./web-client
    restart: no
